/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./index.html",
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        "primary-fixed-dim": "#a7c8ff",
        "surface-dim": "#d8dadc",
        "error-container": "#ffdad6",
        "tertiary-fixed-dim": "#ffb961",
        "on-error": "#ffffff",
        "primary-container": "#003366",
        "surface-tint": "#3a5f94",
        "on-secondary": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "surface-container-highest": "#e0e3e5",
        "surface-variant": "#e0e3e5",
        "surface-container": "#eceef0",
        "on-primary-container": "#799dd6",
        "on-surface": "#191c1e",
        "surface-container-high": "#e6e8ea",
        "inverse-surface": "#2d3133",
        "secondary-container": "#5b97fe",
        "secondary-fixed-dim": "#acc7ff",
        "secondary": "#005bbe",
        "tertiary-container": "#4b2c00",
        "error": "#ba1a1a",
        "on-tertiary-fixed-variant": "#663e00",
        "primary": "#001e40",
        "on-primary": "#ffffff",
        "surface-bright": "#f7f9fb",
        "inverse-primary": "#a7c8ff",
        "on-tertiary-container": "#d98a00",
        "on-secondary-fixed-variant": "#004491",
        "on-background": "#191c1e",
        "on-secondary-container": "#002f68",
        "on-primary-fixed-variant": "#1f477b",
        "tertiary-fixed": "#ffddb9",
        "on-error-container": "#93000a",
        "secondary-fixed": "#d7e2ff",
        "inverse-on-surface": "#eff1f3",
        "primary-fixed": "#d5e3ff",
        "tertiary": "#2e1900",
        "outline-variant": "#c3c6d1",
        "on-secondary-fixed": "#001a40",
        "on-primary-fixed": "#001b3c",
        "on-surface-variant": "#43474f",
        "outline": "#737780",
        "surface": "#f7f9fb",
        "background": "#f7f9fb",
        "surface-container-low": "#f2f4f6",
        "on-tertiary": "#ffffff",
        "on-tertiary-fixed": "#2b1700",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      fontFamily: {
        headline: ["Manrope", "sans-serif"],
        body: ["Plus Jakarta Sans", "sans-serif"],
        label: ["Plus Jakarta Sans", "sans-serif"],
      },
    },
  },
  plugins: [require('@tailwindcss/line-clamp')],
}
