services:
  # app:
  #   build:
  #     context: ..
  #     dockerfile: docker/dockerfile
  #   restart: always
  #   ports:
  #     - "3333:3333"      
    
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=data_db
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ../storage/backup:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1 
              capabilities: [gpu]
    runtime: nvidia
