version: '3'

services:
  # app:
  #   build:
  #     context: ..
  #     dockerfile: docker/dockerfile
  #   restart: always
  #   ports:
  #     - "3333:3333"      
    
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=data_db

