FROM python:3.10

WORKDIR /usr/aplication

COPY requirements.txt .
RUN pip install --upgrade pip && \
    pip install -r requirements.txt

COPY app ./app
COPY infra ./infra
COPY requirements.txt .

CMD ["python", "main.py"]
